# Generated by Django 3.1.6 on 2021-04-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='idmachine',
        ),
        migrations.AddField(
            model_name='temperature',
            name='who',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
